project:
  type: website
  output-dir: docs

website:
  title: "Manoj M"
  favicon: "images/profilepic.jpg"

  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



